sudo: required
services:
  - docker
before_install:
  - docker build -t harry1989/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true harry1989/docker-react npm test
deploy:
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-874380526196"
  bucket_path: "docker-react"
  on:
    branch: master
